version: '3.3'
services:
  nginx:
    build: ./docker-src/nginx
    ports:
    - "8080:80"
    volumes:
    - ./app:/var/www/app
    links:
    - php
  php:
    build: ./docker-src/php
    ports:
    - "9000:9000"
    volumes:
    - ./app:/var/www/app
  app:
    build: ./docker-src/app
    command: sh /install.sh
    volumes:
    - ./app:/var/www/app